Collections:
  - Name: Mlp-Mixer
    Metadata:
      Training Data: ImageNet-1k
      Architecture:
        - MLP
        - Layer Normalization
        - Dropout
    Paper:
      URL: https://arxiv.org/abs/2105.01601
      Title: "MLP-Mixer: An all-MLP Architecture for Vision"
    README: configs/mlp_mixer/README.md
#    Code:
#      URL:  # todo
#      Version:  # todo

Models:
  - Name: mlp-mixer_b16_224_3rdparty_64xb64_in1k
    Metadata:
      FLOPs: 12610000000  # 12.61 G
      Parameters: 59880000  # 59.88 M
    In Collection: Mlp-Mixer
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 76.68
          Top 5 Accuracy: 92.25
        Task: Image Classification
#    Weights: # todo
    Converted From:
      Weights: https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vitjx/jx_mixer_b16_224-76587d61.pth
      Code: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/mlp_mixer.py#L70
    Config: configs/mlp_mixer/mlp_mixer-base_p16_64xb64_in1k.py

  - Name: mlp-mixer_l16_224_3rdparty_64xb64_in1k
    Metadata:
      FLOPs: 44570000000  # 44.57 G
      Parameters: 208200000  # 208.2 M
    In Collection: Mlp-Mixer
    Results:
      - Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 72.34
          Top 5 Accuracy: 88.02
        Task: Image Classification
#    Weights: # todo
    Converted From:
      Weights: https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vitjx/jx_mixer_b16_224_in21k-617b3de2.pth
      Code: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/mlp_mixer.py#L73
    Config: configs/mlp_mixer/mlp_mixer-large_p16_64xb64_in1k.py
